### Listar todas as tarefas
GET http://localhost:5000/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js",
    "descricao": "Estudar Node.js",
    "categoriaId": "6d091456-5a2f-4b5a-98fc-f1a3b50a627d"
}

### Atualizar uma tarefa
PUT http://localhost:5000/tarefas/alterar/98577e52-ed07-4233-a78e-1a41ae41ac2e
Content-Type: application/json

{
    "status": "Concluida"
}

###  Tarefas não concluídas
GET http://localhost:5000/tarefas/naoconcluidas

###  Tarefas concluídas
GET http://localhost:5000/tarefas/concluidas